=== m-marini/fredy/fredy-swing/src/main/resources/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.mmarini.org/fuzzy"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:r="http://www.mmarini.org/fuzzy">

	<element name="rules" type="r:RulesType"></element>
	<complexType name="RulesType">
		<sequence maxOccurs="unbounded" minOccurs="0">
			<element ref="r:rule"></element>
		</sequence>
	</complexType>
	<element name="predicate" type="string"></element>
	<element name="if" type="r:Expression"></element>
	<element name="then" type="r:AssignList"></element>
	<element name="else" type="r:AssignList"></element>
	<element name="not" type="r:Expression"></element>
	<element name="very" type="r:Expression"></element>
	<element name="somewhat" type="r:Expression"></element>
	<element name="known" type="r:Expression"></element>
	<element name="or" type="r:ExpressionList"></element>
	<element name="implies" type="r:ExpressionList"></element>
	<element name="ifonlyif" type="r:ExpressionList"></element>
	<element name="assign" type="string"></element>
	<element name="assign-not" type="string"></element>
	<element name="and" type="r:ExpressionList"></element>

	<complexType name="Expression">
		<sequence maxOccurs="1" minOccurs="1">
			<group ref="r:ExpressionGroup"></group>
		</sequence>
	</complexType>

	<complexType name="ExpressionList">
		<sequence maxOccurs="unbounded" minOccurs="2">
			<group ref="r:ExpressionGroup"></group>
		</sequence>
	</complexType>


	<complexType name="AssignList">
		<choice maxOccurs="unbounded" minOccurs="0">
			<element ref="r:assign"></element>
			<element ref="r:assign-not"></element>
		</choice>
	</complexType>

	<element name="rule" type="r:RuleType"></element>

	<complexType name="RuleType">
		<sequence>
			<element ref="r:if"></element>
			<element ref="r:then"></element>
			<element ref="r:else"></element>
		</sequence>
	</complexType>

	<element name="true" type="r:True"></element>

	<element name="false" type="r:True"></element>

	<element name="unknown" type="r:True"></element>

	<element name="quite-true" type="r:True"></element>

	<element name="quite-false" type="r:True"></element>


	<simpleType name="Confidence">
		<restriction base="double">
			<minInclusive value="0.0"></minInclusive>
			<maxInclusive value="1.0"></maxInclusive>
		</restriction>
	</simpleType>


	<complexType name="True">
		<attribute name="confidence" type="r:Confidence" use="optional"></attribute>
	</complexType>

	<group name="ExpressionGroup">
		<choice>
			<element ref="r:false"></element>
			<element ref="r:quite-false"></element>
			<element ref="r:unknown"></element>
			<element ref="r:quite-true"></element>
			<element ref="r:true"></element>
			<element ref="r:predicate"></element>
			<element ref="r:not"></element>
			<element ref="r:very"></element>
			<element ref="r:somewhat"></element>
			<element ref="r:known"></element>
			<element ref="r:and"></element>
			<element ref="r:or"></element>
			<element ref="r:implies"></element>
			<element ref="r:ifonlyif"></element>
		</choice>
	</group>

</schema>

=== m-marini/fredy/fredy-swing/src/main/resources/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules
	xmlns="http://www.mmarini.org/fuzzy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/fuzzy rules.xsd">
<!--
	I rallentamenti sono dovuti a tempi alti di risposta.
	Possono essere causati dal sistema non performante.
	E' necessario individuare l'elemento che genera i rallentamenti
	Gli elementi di sistema scatenanti possono essere:
	http servers
	application servers
	problemi di rete
	cics lento
	ims lento
	DB2 lento
	Oracle lento
	
-->

	<rule>
		<if>
			<and>
				<predicate>rallentamentiGenerali</predicate>
				<or>
					<predicate>elapsedUrlWasNormali</predicate>
					<predicate>counterUrlWasBassi</predicate>
				</or>
				<predicate>elapsedUrlHttpAlti</predicate>
				<predicate>indicatoriCpuHttpAlti</predicate>
			</and>
		</if>
		<then>
			<assign>problemiCPUHttp</assign>
		</then>
		<else/>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>rallentamentiGenerali</predicate>
				<or>
					<predicate>elapsedUrlWasNormali</predicate>
					<predicate>counterUrlWasBassi</predicate>
				</or>
				<predicate>elapsedUrlHttpAlti</predicate>
				<predicate>indicatoriCpuHttpNormali</predicate>
				<predicate>indicatoriReteHttpAlti</predicate>
			</and>
		</if>
		<then>
			<assign>problemiReteHttp</assign>
		</then>
		<else/>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>rallentamentiGenerali</predicate>
				<or>
					<predicate>elapsedUrlWasAlti</predicate>
					<not>
						<predicate>counterUrlWasAlti</predicate>
					</not>
				</or>
				<predicate>elapsedUrlHttpNormali</predicate>
				<predicate>elapsedCanaliNormali</predicate>
				<predicate>indicatoriCpuWasAlti</predicate>
			</and>
		</if>
		<then>
			<assign>problemiCpuWas</assign>
		</then>
		<else/>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>rallentamentiGenerali</predicate>
				<predicate>elapsedUrlWasAlti</predicate>
				<predicate>indicatoriCpuWasNormali</predicate>
				<predicate>indicatoriReteWasAlti</predicate>
			</and>
		</if>
		<then>
			<assign>problemiReteWas</assign>
		</then>
		<else/>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>rallentamentiGenerali</predicate>
				<predicate>elapsedUrlWasAlti</predicate>
				<predicate>indicatoriCpuWasNormali</predicate>
				<predicate>indicatoriMemoriaWasAlti</predicate>
				<predicate>indicatoriSwapWasAlti</predicate>
				<predicate>indicatoriReteWasNormali</predicate>
			</and>
		</if>
		<then>
			<assign>problemiMemoriaWas</assign>
		</then>
		<else/>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>rallentamentiGenerali</predicate>
				<predicate>elapsedUrlWasAlti</predicate>
				<predicate>indicatoriCpuWasNormali</predicate>
				<predicate>indicatoriMemoriaWasAlti</predicate>
				<predicate>indicatoriSwapWasAlti</predicate>
				<predicate>indicatoriReteWasNormali</predicate>
			</and>
		</if>
		<then>
			<assign>problemiMemoriaWas</assign>
		</then>
		<else/>
	</rule>

</rules>

=== m-marini/fredy/fredy-swing/src/main/resources/animals-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules xmlns="http://www.mmarini.org/fuzzy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/fuzzy rules.xsd">
	<rule>
		<if>
			<or>
				<predicate>peli</predicate>
				<predicate>latte</predicate>
			</or>
		</if>
		<then>
			<assign>mammifero</assign>
		</then>
	</rule>

	<rule>
		<if>
			<or>
				<predicate>piume</predicate>
				<and>
					<predicate>vola</predicate>
					<predicate>uova</predicate>
				</and>
			</or>
		</if>
		<then>
			<assign>uccello</assign>
		</then>
	</rule>

	<rule>
		<if>
			<or>
				<predicate>carne</predicate>
				<and>
					<predicate>denti</predicate>
					<predicate>occhi</predicate>
					<predicate>artigli</predicate>
				</and>
			</or>
		</if>
		<then>
			<assign>carnivoro</assign>
		</then>
	</rule>

	<rule>
		<if>
			<or>
				<and>
					<predicate>mammifero</predicate>
					<predicate>zoccoli</predicate>
				</and>
				<and>
					<predicate>mammifero</predicate>
					<predicate>ruminante</predicate>
				</and>
			</or>
		</if>
		<then>
			<assign>ungulato</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>mammifero</predicate>
				<predicate>carnivoro</predicate>
				<predicate>fulvo</predicate>
				<predicate>macchie</predicate>
			</and>
		</if>
		<then>
			<assign>ghepardo</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>mammifero</predicate>
				<predicate>carnivoro</predicate>
				<predicate>fulvo</predicate>
				<predicate>strisce</predicate>
			</and>
		</if>
		<then>
			<assign>tigre</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>macchie</predicate>
				<predicate>zampe</predicate>
				<predicate>ungulato</predicate>
				<predicate>collo</predicate>
			</and>
		</if>
		<then>
			<assign>giraffa</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>strisce</predicate>
				<predicate>ungulato</predicate>
			</and>
		</if>
		<then>
			<assign>zebra</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>collo</predicate>
				<predicate>uccello</predicate>
				<predicate>bianconero</predicate>
				<not>
					<predicate>vola</predicate>
				</not>
			</and>
		</if>
		<then>
			<assign>struzzo</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<not>
					<predicate>vola</predicate>
				</not>
				<predicate>uccello</predicate>
				<predicate>nuota</predicate>
			</and>
		</if>
		<then>
			<assign>pinguino</assign>
		</then>
	</rule>

	<rule>
		<if>
			<and>
				<predicate>vola</predicate>
				<predicate>uccello</predicate>
			</and>
		</if>
		<then>
			<assign>albatro</assign>
		</then>
	</rule>
</rules>

=== m-marini/fredy/fredy-swing/src/test/resources/org/mmarini/fuzzy/parse/test-rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules xmlns="http://www.mmarini.org/fuzzy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/fuzzy ../../../../../../main/resources/rules.xsd ">
	<rule>
		<if>
			<very>
				<predicate>P1</predicate>
			</very>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<somewhat>
				<predicate>P1</predicate>
			</somewhat>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<known>
				<predicate>P1</predicate>
			</known>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<not>
				<predicate>P1</predicate>
			</not>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<ifonlyif>
				<predicate>P1</predicate>
				<predicate>P2</predicate>
			</ifonlyif>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<implies>
				<predicate>P1</predicate>
				<predicate>P2</predicate>
			</implies>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<and>
				<predicate>P1</predicate>
				<predicate>P2</predicate>
				<predicate>P3</predicate>
			</and>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<or>
				<predicate>P1</predicate>
				<predicate>P2</predicate>
				<predicate>P3</predicate>
			</or>
		</if>
		<then />
		<else />
	</rule>

	<rule>
		<if>
			<predicate>P1</predicate>
		</if>
		<then>
			<assign-not>H1</assign-not>
			<assign>H2</assign>
		</then>
		<else>
			<assign-not>H3</assign-not>
			<assign>E1</assign>
		</else>
	</rule>

	<rule>
		<if>
			<false />
		</if>
		<then />
		<else />
	</rule>
	<rule>
		<if>
			<quite-false />
		</if>
		<then />
		<else />
	</rule>
	<rule>
		<if>
			<unknown />
		</if>
		<then />
		<else />
	</rule>
	<rule>
		<if>
			<quite-true />
		</if>
		<then />
		<else />
	</rule>
	<rule>
		<if>
			<true />
		</if>
		<then />
		<else />
	</rule>
	<rule>
		<if>
			<true confidence="0.8" />
		</if>
		<then />
		<else />
	</rule>
</rules>
